server:
  port: 8040
eureka:
  client:
    region: default
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: "http://localhost:8010/eureka/"
spring:
  application:
    name: Buyer
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"
  datasource:
    url: "jdbc:mysql://localhost:3306/eauction_house_buyer"
    username: "dev"
    password: "password1"