server:
  port: 8060
eureka:
  client:
    region: default
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: "http://localhost:8010/eureka/"
spring:
  application:
    name: listing
  cloud:
    stream:
      kafka:
        binder:
          brokers: "localhost:9092"
          defaultBrokerPort: "9092"
          zkNodes: "zookeeper"
          defaultZkPort: "2181"
      bindings:
        input:
          destination: "PRODUCTS_ON_AUCTION"
        bidinput:
          destination: "BIDS_PLACED_BY_BUYER"  
      default:
        contentType: "application/json"
  data:
    mongodb:
      port: "27017"
      host: "localhost"
      database: "EAUCTION_HOUSE"
  