version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks: 
      - mynetwork
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    networks: 
      - mynetwork
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=citizix
      - MONGO_INITDB_ROOT_PASSWORD=S3cret
    networks: 
      - mynetwork
  discovery-service:
    image: discovery-service
    container_name: discovery-service
    restart: on-failure
    ports:
      - "8010:8010"
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8010/eureka  
    networks: 
      - mynetwork
  configuration-service:
    image: configuration-service
    container_name: configuration-service
    depends_on: 
      discovery-service:
        condition: service_started
    ports:
      - "8888:8888"
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8010/eureka
    networks: 
      - mynetwork
  gateway:
    image: gateway-service
    container_name: gateway-service
    restart: on-failure
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8010/eureka
    depends_on: 
      configuration:
        condition: service_started
      discovery:
        condition: service_started
    ports:
      - "8081:8081"
    networks: 
      - mynetwork
  listing-service:
    image: listing-service
    container_name: listing-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8010/eureka
    depends_on: 
      configuration:
        condition: service_started
      discovery:
        condition: service_started
    ports:
      - "8060:8060"
    networks: 
      - mynetwork
networks: 
  mynetwork:
    driver: bridge  