version: '3'
services:
  gateway-service:
    image: eauctionathackfse/gateway-service
    container_name: gateway-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://100.20.149.16:8010/eureka
    ports:
      - "8081:8081"
  auth-service:
    image: eauctionathackfse/auth-service
    container_name: auth-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://100.20.149.16:8010/eureka
    ports:
      - "8090:8090"
  seller-service:
    image: eauctionathackfse/seller-service
    container_name: seller-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://100.20.149.16:8010/eureka
    ports:
      - "8020:8020"
  product-service:
    image: eauctionathackfse/product-service
    container_name: product-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://100.20.149.16:8010/eureka
    ports:
      - "8030:8030"
  listing-service:
    image: eauctionathackfse/listing-service
    container_name: listing-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://100.20.149.16:8010/eureka
    ports:
      - "8060:8060"
  buyer-service:
    image: eauctionathackfse/buyer-service
    container_name: buyer-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://100.20.149.16:8010/eureka
    ports:
      - "8040:8040"
  bid-service:
    image: eauctionathackfse/bid-service
    container_name: bid-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://100.20.149.16:8010/eureka
    ports:
      - "8050:8050"    
networks:
  default:
    external:
      name: eauctionHouseNet