version: '3'
services:
  seller-service:
    image: seller-service
    container_name: seller-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8010/eureka
    ports:
      - "8020:8020"
  product-service:
    image: product-service
    container_name: product-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8010/eureka
    ports:
      - "8030:8030"
  listing-service:
    image: listing-service
    container_name: listing-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8010/eureka
    ports:
      - "8060:8060"
networks:
  default:
    external:
      name: eauctionHouseNet