version: '3'
services:
  listing-service:
    image: eauctionathackfse/listing-service
    container_name: listing-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8010/eureka
    ports:
      - "8060:8060"
networks:
  default:
    external:
      name: eauctionHouseNet