server: 
  port: 8888  
spring:
  application:
    name: configuration-service
  # Profile creation. Currently will load the configuration file local file system. 
  # Later we will change the value to Git. So that it can load the same from the git
  profiles:
    active: native
  # Security Configuration   
  security:
    user:
      name: eauctionUsr
      password: password1
      
eureka:
  client:
    region: default
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: "http://localhost:8010/eureka/" 