server:
  port: 8080
eureka:
  client:
    region: default
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: "http://discovery:8010/eureka/"
jwt:
  secret: "SECRET"
  token:
    accessToken:
      validity: "720000000"
    refreshToken:
      validity: "86400000"
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"             