server:
  port: 8030
eureka:
  client:
    region: default
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: "http://localhost:8010/eureka/"
spring:
  application:
    name: product
  cloud:
    stream:
      kafka:
        binder:
          brokers: "localhost:9092"
          defaultBrokerPort: "9092"
          zkNodes: "zookeeper"
          defaultZkPort: "2181"
      bindings:
        output:
          destination: "PRODUCTS_ON_AUCTION" 
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"
  datasource:
    url: "jdbc:mysql://localhost:3306/eauction_house_product"
    username: "dev"
    password: "password1"
 