server:
  port: 8020
eureka:
  client:
    region: default
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: "http://discovery-service:8010/eureka/"
spring:
  application:
    name: seller
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://mysql-container:3306/eauction_house_seller"
    username: "root"
    password: "password1"