spring:
  application:
    name: auth
  profiles:
    active: dev
  config:
    import: "configserver:http://configuration-service:8888"
  cloud:
    config:
      uri: http://configuration-service:8888/
      username: eauctionUsr
      password: password1
