spring:
  application:
    name: listing
  profiles:
    active: dev
  config:
    import: "configserver:http://100.20.149.16:8888"
  cloud:
    config:
      uri: http://100.20.149.16:8888/
      username: eauctionUsr
      password: password1
